package com.myteam.myproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubformDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean checkbox;
	private java.lang.String textbox;
	private java.lang.String textarea;
	private int integerbox;
	private double decimalbox;
	private java.util.Date datepicker;
	private double slider;
	private java.lang.String listbox;
	private java.lang.String radiogroup;

	private java.util.List<com.myteam.myproject.NestedDO> multiplesubform;

	public SubformDO() {
	}

	public boolean isCheckbox() {
		return this.checkbox;
	}

	public void setCheckbox(boolean checkbox) {
		this.checkbox = checkbox;
	}

	public java.lang.String getTextbox() {
		return this.textbox;
	}

	public void setTextbox(java.lang.String textbox) {
		this.textbox = textbox;
	}

	public java.lang.String getTextarea() {
		return this.textarea;
	}

	public void setTextarea(java.lang.String textarea) {
		this.textarea = textarea;
	}

	public int getIntegerbox() {
		return this.integerbox;
	}

	public void setIntegerbox(int integerbox) {
		this.integerbox = integerbox;
	}

	public double getDecimalbox() {
		return this.decimalbox;
	}

	public void setDecimalbox(double decimalbox) {
		this.decimalbox = decimalbox;
	}

	public java.util.Date getDatepicker() {
		return this.datepicker;
	}

	public void setDatepicker(java.util.Date datepicker) {
		this.datepicker = datepicker;
	}

	public double getSlider() {
		return this.slider;
	}

	public void setSlider(double slider) {
		this.slider = slider;
	}

	public java.lang.String getListbox() {
		return this.listbox;
	}

	public void setListbox(java.lang.String listbox) {
		this.listbox = listbox;
	}

	public java.lang.String getRadiogroup() {
		return this.radiogroup;
	}

	public void setRadiogroup(java.lang.String radiogroup) {
		this.radiogroup = radiogroup;
	}

	public java.util.List<com.myteam.myproject.NestedDO> getMultiplesubform() {
		return this.multiplesubform;
	}

	public void setMultiplesubform(
			java.util.List<com.myteam.myproject.NestedDO> multiplesubform) {
		this.multiplesubform = multiplesubform;
	}

	public SubformDO(boolean checkbox, java.lang.String textbox,
			java.lang.String textarea, int integerbox, double decimalbox,
			java.util.Date datepicker, double slider, java.lang.String listbox,
			java.lang.String radiogroup,
			java.util.List<com.myteam.myproject.NestedDO> multiplesubform) {
		this.checkbox = checkbox;
		this.textbox = textbox;
		this.textarea = textarea;
		this.integerbox = integerbox;
		this.decimalbox = decimalbox;
		this.datepicker = datepicker;
		this.slider = slider;
		this.listbox = listbox;
		this.radiogroup = radiogroup;
		this.multiplesubform = multiplesubform;
	}

}